"""fix_nullable_average_prices

Revision ID: bcc4ede16acb
Revises: b241a5f8341e
Create Date: 2026-01-08 11:27:56.192487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc4ede16acb'
down_revision = 'b241a5f8341e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('average_spot_entry_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('average_futures_entry_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('total_entries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('funding_payments_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('low_fr_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('consecutive_low_fr',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('idx_positions_crypto'))
        batch_op.create_index(batch_op.f('ix_positions_crypto'), ['crypto'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_crypto'))
        batch_op.create_index(batch_op.f('idx_positions_crypto'), ['crypto'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('consecutive_low_fr',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.alter_column('low_fr_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.alter_column('funding_payments_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.alter_column('total_entries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
        batch_op.alter_column('average_futures_entry_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('average_spot_entry_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
