"""initial_schema

Revision ID: d2141da78c5d
Revises: 
Create Date: 2026-01-03 23:16:38.534530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2141da78c5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crypto', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklist_crypto'), ['crypto'], unique=True)

    op.create_table('closed_positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crypto', sa.String(length=20), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('close_timestamp', sa.DateTime(), nullable=False),
    sa.Column('spot_entry_price', sa.Float(), nullable=False),
    sa.Column('futures_entry_price', sa.Float(), nullable=False),
    sa.Column('spot_exit_price', sa.Float(), nullable=False),
    sa.Column('futures_exit_price', sa.Float(), nullable=False),
    sa.Column('spot_qty', sa.Float(), nullable=False),
    sa.Column('futures_qty', sa.Float(), nullable=False),
    sa.Column('entry_spread_pct', sa.Float(), nullable=False),
    sa.Column('close_spread_pct', sa.Float(), nullable=False),
    sa.Column('net_pnl', sa.Float(), nullable=False),
    sa.Column('price_pnl', sa.Float(), nullable=False),
    sa.Column('spot_pnl', sa.Float(), nullable=True),
    sa.Column('futures_pnl', sa.Float(), nullable=True),
    sa.Column('funding_pnl', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('funding_payments_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('closed_positions', schema=None) as batch_op:
        batch_op.create_index('idx_closed_positions_crypto_date', ['crypto', 'close_timestamp'], unique=False)
        batch_op.create_index('idx_closed_positions_date', ['close_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_closed_positions_crypto'), ['crypto'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('crypto', sa.String(length=20), nullable=False),
    sa.Column('spot_entry_price', sa.Float(), nullable=False),
    sa.Column('futures_entry_price', sa.Float(), nullable=False),
    sa.Column('spot_qty', sa.Float(), nullable=False),
    sa.Column('futures_qty', sa.Float(), nullable=False),
    sa.Column('entry_spread_pct', sa.Float(), nullable=False),
    sa.Column('entry_timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_funding_check_time', sa.DateTime(), nullable=True),
    sa.Column('funding_payments_count', sa.Integer(), nullable=False),
    sa.Column('low_fr_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_low_fr', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('idx_positions_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_crypto'), ['crypto'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_crypto'))
        batch_op.drop_index('idx_positions_created')

    op.drop_table('positions')
    with op.batch_alter_table('closed_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_closed_positions_crypto'))
        batch_op.drop_index('idx_closed_positions_date')
        batch_op.drop_index('idx_closed_positions_crypto_date')

    op.drop_table('closed_positions')
    with op.batch_alter_table('blacklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklist_crypto'))

    op.drop_table('blacklist')
    # ### end Alembic commands ###
